/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ScplButton {}
  interface ScplButtonAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'ScplButton': Components.ScplButton;
  }

  interface StencilIntrinsicElements {
    'scpl-button': Components.ScplButtonAttributes;
  }


  interface HTMLScplButtonElement extends Components.ScplButton, HTMLStencilElement {}
  var HTMLScplButtonElement: {
    prototype: HTMLScplButtonElement;
    new (): HTMLScplButtonElement;
  };

  interface HTMLElementTagNameMap {
    'scpl-button': HTMLScplButtonElement
  }

  interface ElementTagNameMap {
    'scpl-button': HTMLScplButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
